### ISSUE TITLE
Horizontal and vertical scrollbar  are not displayed on Linux

### ISSUE THREAD

**Issue by ibadi-id** [KevinVandy/mantine-react-table#239]
### mantine-react-table version

v2.0.0-alpha.9

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Horizontal and vertical scrollbars are displayed on windows but not on linux

### Minimal, Reproducible Example - (Optional, but Recommended)

Set mantineTableContainerProps config :
```
mantineTableContainerProps: { style: { maxHeight: '500px' } },
```

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/mantine-react-table/assets/82359656/ca7e2799-17f2-4adc-b064-8f7fe7f88b70)
![image](https://github.com/KevinVandy/mantine-react-table/assets/82359656/a091526e-55e2-4c2c-b965-95cf89e6388e)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Isn't this just a browser/OS thing? You can add CSS to force scrollbars to show or look how you want to on your site.

I usually paste this in my global CSS file for all of my websites so that it always looks like the default MacOs scrollbars for everyone.

```css
::-webkit-scrollbar-track {
  background-color: transparent;
}

::-webkit-scrollbar {
  right: 0;
  width: 12px;
  height: 12px;
}

::-webkit-scrollbar-thumb {
  background-color: #999;
  border-radius: 8px;
  width: 12px;
  height: 12px;
}
```
