### ISSUE TITLE
Row dividers are not visible in Firefox

### ISSUE THREAD

**Issue by iscy** [KevinVandy/mantine-react-table#327]
### mantine-react-table version

2.0.0-beta.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

1. Open the basic example of MantineReactTable v2+ in Chrome
2. Open the same link in Firefox
 => Dividers are not visible in Firefox

### Minimal, Reproducible Example - (Optional, but Recommended)

https://v2.mantine-react-table.com/docs/examples/basic

### Screenshots or Videos (Optional)

![Screenshot_20240507_142430](https://github.com/KevinVandy/mantine-react-table/assets/294710/d17e01df-e347-4704-ba03-7d5e20ba350a)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by alessandrojcm** [comment]
This looks like a bug in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=688556, the CSS is not doing anything special here so I am inclined to believe it's a bug with the browser.

**Comment by davidroeca** [comment]
I've stumbled across this issue as well, and found a workaround within my app for now -- I needed to unset some backgrounds. The `paper` background will take precedence here. While this is most definitely a bug in firefox, it's more than 10 years old and hasn't been fixed.

```css
/*  styles.module.css */
.table {
  /* ... */
  /* Resolve https://github.com/KevinVandy/mantine-react-table/issues/327 */
  background-color: unset !important;
  tbody, thead {
    /* Resolve https://github.com/KevinVandy/mantine-react-table/issues/327 */
    background-color: unset !important;
  }
  tr {
    /* Resolve https://github.com/KevinVandy/mantine-react-table/issues/327 */
    background-color: unset !important;
  }
  td {
    /* Resolve https://github.com/KevinVandy/mantine-react-table/issues/327 */
    /* see https://bugzilla.mozilla.org/show_bug.cgi?id=688556#c43 */
    background-clip: padding-box;
  }
}
```

Then these styles get used in MRT_TableOptions:

```ts
  import styles from './styles.module.css'
  export const getMyMRTOptions = <TData extends MRT_RowData>(
    config: MRTConfig = {},
  ): Partial<MRT_TableOptions<TData>> => ({
    // ...
    mantineTableProps: {
      className: styles.table,
    },
  })
```
